### PR TITLE
Homework_8

### PR DESCRIPTION
**Pull request by IsaevMH**

### CODE REVIEW

**Comment by alla-blinkova** [comment]
Tests don't contain preconditions and postconditions (see 2.2 in the task description)

**Comment by alla-blinkova** [comment]
"SendTextFromArray" test - Why did you combine each input text with each expected result? 
It looks like 1st input should relate to the 1st expected result and so on.

**Comment by alla-blinkova** [comment]
Tests with data providers - 
If one launch fails (e.g. 1st in the data set), the whole test fails immediately, but it should not (see 2.5 in the task description)

**Review by alla-blinkova — CHANGES_REQUESTED** [review]
Changes according to the comments are required

**Comment by IsaevMH** [comment]
> 
> 
> "SendTextFromArray" test - Why did you combine each input text with each expected result?
> It looks like 1st input should relate to the 1st expected result and so on.



> 
> 
> Tests with data providers -
> If one launch fails (e.g. 1st in the data set), the whole test fails immediately, but it should not (see 2.5 in the task description)

Issue was fixed

**Comment by alla-blinkova** [comment]
One more comment about "SendTextFromArray" test. Why do you need a nested loop in the script?

**Review by alla-blinkova — APPROVED** [review]
Done, can be merged

**Pull request closed without merging**
